### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by gilokk0** [instafluff/ChatBlocks#21]
It would be nice if we could ***count spaces*** instead of using **index**, which just gives the position of the given letter/text/etc, not really helping to resolve the math command problem.

**Comment by gilokk0** [comment]
The new text_contains does what I wanted from regex. But what I wrote above still aplies.

**Comment by daanbreur** [comment]
I do not understant your idea.  Can you please explain it a bit more clearly?



In the following message structure 
```

## Is a new block needed?

## What does the new block do? And what inputs are needed.

## What does the new block return?

```

Thank you. If you do this I can implement it and ask instafluff for his thoughts.

**Comment by gilokk0** [comment]
## Is a new block needed?
To do what I want, sure. Now, if it's needed, I don't know.

## What does the new block do? And what inputs are needed.
The block would count the number of spaces in a given string. [This](https://www.w3resource.com/java-exercises/basic/java-basic-exercise-38.php) is an example (it may need some modifications), but there are more refined examples if it's just counting the number of spaces. The input would be a string (in my case a chatmessage).

## What does the new block return?
Right now I only need the block to return the number of spaces in a string, but maybe we could choose between letters, spaces, numbers and others (symbols).

**Comment by daanbreur** [comment]
Thanks i think i get it... a new block in the `text category` that says:  count amount `insert a string here` in `stringvariable`

**Comment by gilokk0** [comment]
That is pretty much it... Sorry for not giving a more detailed answer, I'm still not at my computer and it looks like that I am not going to be able to be at my computer for a long time...

**Comment by daanbreur** [comment]
Ok thanks. I'll think about it because. It's almost getting to the point you only need a few blocks. And aren't really "coding" it.

I will ask instafluff for his opinion

**Comment by instafluff** [comment]
A "count" block for how many occurrences there are of a string is probably a good addition :O

**Comment by daanbreur** [comment]
Okey :D

**Comment by daanbreur** [comment]
**working on it**

**Comment by gilokk0** [comment]
The example I gave doesn't need much coding, no, but most of the other examples I found actually used regular expressions.

And I honestly (sorry if I sound rude) would like to know how to do this in a few blocks. Really, that would help me a lot. Because using index to find the position of a character doesn't help me (in this case, I mean).
![mathcommand](https://user-images.githubusercontent.com/17620548/88097926-d9eae300-cb90-11ea-995d-9a6ca8d81807.png)
Use that block in the command instead of the other one that doesn't help me, I meant.

Again, sorry if I sound rude, but I'm not finding any other way to put this into words right now...

**Comment by gilokk0** [comment]
I was writing that message before I saw the other ones, oops...

**Comment by daanbreur** [comment]
i was thinking meaby it willl become to much ```place only a few under eachother and done```
But this one is okey

**Comment by daanbreur** [comment]
# DONE
*Status: not Merged*

**Comment by daanbreur** [comment]
@instafluff  @gilokk0

**Comment by daanbreur** [comment]
# DONE, MERGED, LOCKED

**Comment by daanbreur** [comment]
Thanks
