### ISSUE TITLE
idea: make a call to users and get its teams

### ISSUE THREAD

**Issue by rochacbruno** [instafluff/ChatBlocks#22]
Hi, I would like to automatically shout-out for the members of livecoders team using ChatBlocks

I see that we can call the /users API and get a list of all the teams that user is included, so to allow that we need something like:

`pseudo code`
```rust
on_chat {

    if is_first_message(username) {

        if user.teams.contains("livecoders") {

             say(
               "Checkout {username} a member of live coders team! https://twitch.tv/{username}"
             )

        }

    }

}
 

```

**Comment by daanbreur** [comment]
Good Suggestion.
I will work on it later

**Comment by daanbreur** [comment]
@rochacbruno it will be hard to implement this we need to look into this a bit more

**Comment by daanbreur** [comment]
@rochacbruno i think got it kinda wokring... im now gonna make it into a block :D :instafWaa:

**Comment by daanbreur** [comment]
# DONE
*Status: not Merged*

**Comment by daanbreur** [comment]
# MERGED

**Comment by daanbreur** [comment]
Can you lock / close this issue. For reason: resolved

**Comment by rochacbruno** [comment]
Hi @daanbreur I will test it soon once I get back to streaming this week.

**Comment by daanbreur** [comment]
Thanks  👍
